name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
          
      - name: Run test
        run: cd ./backend && npm test

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gautamzero/digital-library:v1

      - name: Push docker image
        run: docker push gautamzero/digital-library:v1
